### ISSUE TITLE
Upgrade to v5.1.5

### ISSUE THREAD

**Issue by fbruetting** [flathub/org.kicad_pcb.KiCad#23] opened 2019-12-20 20:08 UTC
Would be neat!

**Comment by jmaibaum** [comment] 2019-12-31 11:16
A pull request exists in #22.

**Comment by jmaibaum** [comment] 2020-01-23 18:20
And a second one exists in #24 (which also switches source download to Gitlab, where the project has been moved).

**Comment by jmaibaum** [comment] 2020-02-19 18:14
@bilelmoussaoui Thanks for merging #24! Something seems to have been going wrong during the build though, see https://flathub.org/builds/#/builders/32/builds/15487

According to https://flathub.org/builds/#/builders/19/builds/1818, the "Generate deltas" step timed out after 20:00 mins. Since this has never happened during the test builds during the PR phase, I have no idea what went wrong. Do you have any idea what has happened?

**Comment by bilelmoussaoui** [comment] 2020-02-19 18:26
I triggered a new build, let's see if we can reproduce that.

**Comment by jmaibaum** [comment] 2020-02-19 21:26
Looks as if all is OK now, see https://flathub.org/builds/#/builders/32/builds/15522

Thanks @bilelmoussaoui!

**Comment by bilelmoussaoui** [comment] 2020-02-19 22:38
Perfext, we can close this issue then.

**Closed as completed by bilelmoussaoui** 2020-02-19 22:38 UTC
